version: '3'

services:
  # HYDRA MIGRATIONS
  hydra-migrate:
    image: oryd/hydra
    environment:
      - DSN=cockroach://root@cockroachd:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure
    networks: 
      - hydra-internal

  # HYDRA SERVER
  hydra:
    image: oryd/hydra
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port (should be protected behind a proxy)
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    environment:
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_CONSENT=http://localhost:8000/api/v1/oauth/consent
      - URLS_LOGIN=http://localhost:8000/api/v1/oauth/login
      - URLS_LOGOUT=http://localhost:8000/api/v1/oauth/logout
      - DSN=cockroach://root@cockroachd:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
      - SERVE_COOKIES_SAME_SITE_MODE=Lax
      - LOG_LEVEL=debug
      - LOG_LEAK_SENSITIVE_VALUES=true
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
      # CORS
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SERVE_PUBLIC_CORS_DEBUG=true
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://localhost:8001
      - SERVE_PUBLIC_CORS_ALLOWED_HEADERS=Authorization,Content-Type
      #- SERVE_PUBLIC_CORS_ALLOWED_METHODS=POST,GET,PUT,DELETE
      - SERVE_ADMIN_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_DEBUG=true
      - SERVE_ADMIN_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://localhost:8001
      - SERVE_ADMIN_CORS_ALLOWED_HEADERS=Authorization,Content-Type
    networks: 
      - hydra-internal

  # COCKROACH DB
  cockroachd:
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    volumes: 
      - cockroach-data:/cockroach/cockroach-data
    networks: 
      - hydra-internal

  # ADMINER
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks: 
      - hydra-internal

  # ODYSSEUS SERVER
  odysseus-server:
    image: ghcr.io/simoneromano96/odysseus-identity-manager/server:0.7.1-beta.4
    environment:
      APP_SERVER_PORT: 80
      APP_SERVER_CLIENTURI: http://localhost:8001
      APP_HYDRA_URI: http://localhost:4445
      APP_HYDRA_USERNAME: user
      APP_HYDRA_PASSWORD: password
      APP_MONGO_URI: mongodb://root:2B3s2Ih1YYxO@mongo
      APP_MONGO_DATABASE: odysseus
      APP_REDIS_URI: redis:6379
      APP_SESSION_SECRET: secret
      APP_SMTP_DOMAIN: mail.yourdomain.com
      APP_SMTP_USERNAME: system@mail.yourdomain.com
      APP_SMTP_PASSWORD: systempassword
      APP_SMTP_ADDRESS: system@mail.yourdomain.com
      APP_SMTP_ALIAS: Odysseus System
    networks: 
      - odysseus-internal

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks: 
      - odysseus-internal

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks: 
      - odysseus-internal
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 8081:8081
    networks: 
      - odysseus-internal
  
  # ODYSSEUS CLIENT
  # odysseus-client:
  #   image: ghcr.io/simoneromano96/odysseus-identity-manager/client:0.5.2
  #   networks:
  #     - odysseus-internal
  #   ports:
  #     - 8001:80

networks:
  odysseus-internal:
  hydra-internal:

volumes:
  cockroach-data:
  mongo-data:
